version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Node code...1
      - pwd
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo 15

artifacts:
  files:
    - '**/*'

